on: [push]
jobs:
  PublishImage:
    runs-on: ubuntu-latest
    steps:
      - name: Build Dockerfile and Push to The Hub
        uses: beehivewarrior/docker-hub-builder@v1.0
        with:
          DOCKERHUB_USERNAME: robbelouwet
          DOCKERHUB_TOKEN: dckr_pat_bWIpIMrHodqJ6T2ln8hF3TkQ8Mg
          BASE_TAG: harpocrates
          TAG_NAME: $(git rev-parse --short "$GITHUB_SHA")
          IMAGE_NAME: harpocrates
          DOCKERFILE_PATH: ./Harpocrates/Dockerfile
